movie_app/urls.py
from django.urls import path
from . import views

app_name = 'movie_app'

urlpatterns = [
    path('upcoming_movies/', views.upcoming_movies, name='upcoming_movies'),
    path('set_language/', views.set_language, name='set_language'),
    path('', views.display_movies, name='display_movies'),
    path('details/<int:movie_id>/', views.display_movie_details, name='movie_details'),
]

movie_recommendation/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.homepage, name='home'),
    path('about/', views.about, name='about'),
    path('admin/', admin.site.urls, name='admin'),
    path('users/', include('user_app.urls')),
    path('reviews/', include('review_app.urls')),
    path('search/', views.search_view, name='search'),
    path('movies/', include(('movie_app.urls', 'movie_app'), namespace='movie_app')),
    path('movies/search/', views.search_movies, name='search_movies'),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_app/urls.py
from django.urls import path
from . import views

app_name = 'user_app'

urlpatterns = [
    path('details/<int:user_id>/', views.display_user_details_page, name='user_details'),
    path('register/', views.display_register_page, name='register'),
    path('login/', views.display_login_page, name='login'),
    path('logout/', views.display_logout_page, name='logout'),
]

templates/about.html
{% extends 'base.html' %}

{% block title %}
    About
{% endblock %}

{% block content %}
<h1>About Page</h1>
<p>This is a movie recommendation app. It uses machine learning to recommend movies based on user preferences</p>
{% endblock %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
        Movies Recommendation
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<header>
    <nav>
        <a href="/">Home</a>
        <a href="{% url 'movie_app:display_movies' %}">Movies</a>
        <a href="{% url 'movie_app:upcoming_movies' %}">Upcoming Movies</a>
        <a href="{% url 'about' %}">About</a>
        {% if user.is_authenticated %}
            <a href="{% url 'user_app:user_details' user_id=user.user_id%}">User Details</a>
            <span>Welcome, {{ user.login }}</span>
            <a href="{% url 'user_app:logout' %}" class="logout-button">Logout</a>
        {% else %}
            <a href="{% url 'user_app:login' %}">User Details</a>
            <a href="{% url 'user_app:login' %}" class="login-button">
                <i class="bi bi-person-fill"></i> Login
            </a>
        {% endif %}
    </nav>
           <form method="post" action="{% url 'movie_app:set_language' %}">
    {% csrf_token %}
    <select name="language">
        <option value="en" {% if request.session.language == "en" %}selected{% endif %}>English</option>
        <option value="pl" {% if request.session.language == "pl" %}selected{% endif %}>Polski</option>
        <option value="de" {% if request.session.language == "de" %}selected{% endif %}>Deutsch</option>
    </select>
    <button type="submit">Change Language</button>
</form>

<p>Wybrany język: {{ request.session.language }}</p>
    <div class="top-bar">
        <div class="search-bar">
            <form action="/search" method="get" autocomplete="off">
                <input type="text" id="search-input" name="q" placeholder="Search..." autocomplete="off">
                <button type="submit">Search</button>
            </form>
            <div id="search-results"></div>
            <script>
                document.getElementById('search-input').addEventListener('input', function() {
                    var query = this.value;
                    if (query.length > 1) {
                        fetch(`/movies/search/?q=${encodeURIComponent(query)}`)
                            .then(response => response.json())
                            .then(data => {
                                let resultsHtml = data.map(item => `<div><a href="/movies/details/${item.id}/">${item.title}</a></div>`).join('');
                                document.getElementById('search-results').innerHTML = resultsHtml;
                            })
                            .catch(error => console.error('Error:', error));
                    } else {
                        document.getElementById('search-results').innerHTML = '';
                    }
                });
            </script>
        </div>
    </div>
</header>
<main>
    {% block content %}
    {% endblock %}
</main>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    Home Page
{% endblock %}

{% block content %}
<h1>Home Page</h1>

{% if user.is_authenticated and recommended_movies|length > 0 %}
<h2>Recommended for You</h2>
<div class="movie-grid">
    {% for movie in recommended_movies %}
    <div class="movie-item">
        <a href="{% url 'movie_app:movie_details' movie_id=movie.movie_id %}">
            <img class="poster" src="{{ movie.photo_url }}" alt="{{ movie.title }}">
            <h3>{{ movie.title }}</h3>
        </a>
        <p>Rating: {{ movie.rating }}</p>
        <div class="star-rating">
            {% for star in movie.get_star_rating.full_stars %}
                <span class="star filled">&#9733;</span>
            {% endfor %}
            {% if movie.get_star_rating.half_stars %}
                <span class="star">&#9733;</span>
            {% endif %}
            {% for star in movie.get_star_rating.empty_stars %}
                <span class="star">&#9734;</span>
            {% endfor %}
        </div>
        <p>Votes: {{ movie.votes }}</p>
    </div>
    {% endfor %}
</div>
{% endif %}

<h2>Most Popular Movies</h2>
<div class="movie-grid">
    {% for movie in popular_movies %}
    <div class="movie-item">
        <a href="{% url 'movie_app:movie_details' movie_id=movie.movie_id %}">
            <img class="poster" src="{{ movie.photo_url }}" alt="{{ movie.title }}">
            <h3>{{ movie.title }}</h3>
        </a>
        <p>Rating: {{ movie.rating }}</p>
        <div class="star-rating">
            {% for star in movie.get_star_rating.full_stars %}
                <span class="star filled">&#9733;</span>
            {% endfor %}
            {% if movie.get_star_rating.half_stars %}
                <span class="star">&#9733;</span>
            {% endif %}
            {% for star in movie.get_star_rating.empty_stars %}
                <span class="star">&#9734;</span>
            {% endfor %}
        </div>
        <p>Votes: {{ movie.votes }}</p>
    </div>
    {% endfor %}
</div>

<h2>Latest Reviews</h2>
<div class="review-grid">
    {% for review in latest_reviews %}
    <div class="review-item">
        <h3>{{ review.movie.title }}</h3>
        <p><strong>User:</strong> {{ review.user.display_name }}</p>
        <p class="review-item-content"><strong>Review:</strong> {{ review.review_text }}</p>
        <p><strong>Rating:</strong> {{ review.rating }}</p>
        <div class="star-rating">
            {% for star in review.get_star_rating.full_stars %}
                <span class="star filled">&#9733;</span>
            {% endfor %}
            {% if review.get_star_rating.half_stars %}
                <span class="star">&#9733;</span>
            {% endif %}
            {% for star in review.get_star_rating.empty_stars %}
                <span class="star">&#9734;</span>
            {% endfor %}
        </div>
        <p><strong>Added on:</strong> {{ review.review_date|date:"F d, Y" }}</p>
    </div>
    {% endfor %}
</div>

{% endblock %}