movie_app/urls.py
from django.urls import path
from . import views

app_name = 'movie_app'

urlpatterns = [
    path('upcoming_movies/', views.upcoming_movies, name='upcoming_movies'),
    path('set_language/', views.set_language, name='set_language'),
    path('', views.display_movies, name='display_movies'),
    path('details/<int:movie_id>/', views.display_movie_details, name='movie_details'),
]

movie_recommendation/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.homepage, name='home'),
    path('about/', views.about, name='about'),
    path('admin/', admin.site.urls, name='admin'),
    path('users/', include('user_app.urls')),
    path('reviews/', include('review_app.urls')),
    path('search/', views.search_view, name='search'),
    path('movies/', include(('movie_app.urls', 'movie_app'), namespace='movie_app')),
    path('movies/search/', views.search_movies, name='search_movies'),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

review_app/urls.py
from django.urls import path, include
from . import views

app_name = 'review_app'

urlpatterns = [
    path('add_review/<int:movie_id>/', views.add_review, name='add_review'),
    path('add_comment/<int:review_id>/', views.add_comment, name='add_comment'),


]

user_app/urls.py
from django.urls import path
from . import views

app_name = 'user_app'

urlpatterns = [
    path('details/<int:user_id>/', views.display_user_details_page, name='user_details'),
    path('register/', views.display_register_page, name='register'),
    path('login/', views.display_login_page, name='login'),
    path('logout/', views.display_logout_page, name='logout'),
]

movie_app/models.py
from django.db import models
from django.apps import apps

class Movies(models.Model):
    movie_id = models.AutoField(primary_key=True)
    title = models.TextField()
    production_year = models.IntegerField(blank=True, null=True)
    rating = models.FloatField(blank=True, null=True)
    certificate = models.TextField(blank=True, null=True)
    duration = models.IntegerField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    votes = models.IntegerField(blank=True, null=True)
    photo_url = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'movies'

    def __str__(self):
        return self.title

    @classmethod
    def get_distinct_movies(cls):
        all_movies = list(cls.objects.all())
        unique_movies = []
        seen_titles = set()
        for movie in all_movies:
            if movie.title not in seen_titles:
                unique_movies.append(movie)
                seen_titles.add(movie.title)
        return unique_movies

    @classmethod
    def get_popular_movies(cls):
        distinct_movies = cls.get_distinct_movies()
        scored_movies = [(movie, movie.rating * movie.votes) for movie in distinct_movies if
                         movie.rating is not None and movie.votes is not None]
        scored_movies.sort(key=lambda x: x[1], reverse=True)
        return [movie for movie, score in scored_movies[:3]]

    def get_star_rating(self):
        if self.rating is None:
            return {
                'full_stars': [],
                'half_stars': 0,
                'empty_stars': range(5)
            }
        full_stars = int(self.rating)
        decimal_part = self.rating - full_stars

        # Calculate half star
        if 0.25 <= decimal_part < 0.75:
            half_stars = 1
        else:
            half_stars = 0

        # Calculate empty stars
        empty_stars = 5 - full_stars - half_stars

        return {
            'full_stars': range(full_stars),
            'half_stars': half_stars,
            'empty_stars': range(empty_stars)
        }

    @classmethod
    def get_movie(cls, id):
        return cls.objects.get(pk=id)

    @classmethod
    def get_movies(cls):
        return cls.objects.all()

    @classmethod
    def get_movie_details(cls, id):
        movie = cls.get_movie(id)
        genres = Genredetails.objects.filter(genre__movie=movie)
        directors = Directorsdetails.objects.filter(directors__movie=movie)
        casts = Moviecastdetails.objects.filter(moviecast__movie=movie)
        movie_details = {
            'movie': movie,
            'genres': genres,
            'directors': directors,
            'casts': casts
        }
        return movie_details

    @classmethod
    def get_movies_details(cls):
        movies = cls.objects.all()

        movies_details = []
        for movie in movies:
            genres = Genredetails.objects.filter(genre__movie=movie)
            directors = Directorsdetails.objects.filter(directors__movie=movie)
            casts = Moviecastdetails.objects.filter(moviecast__movie=movie)
            Reviews = apps.get_model('review_app', 'Reviews')
            reviews = Reviews.get_review_for_movie(movie)
            movie_details = {
                'movie': movie,
                'genres': genres,
                'directors': directors,
                'casts': casts,
                'reviews': reviews,
            }

            movies_details.append(movie_details)
        return movies_details

    @classmethod
    def get_movies_head(cls):
        return cls.get_movies_details()[:100]

    @classmethod
    def query_movies(cls, genre=None, production_year=None, cast=None, director=None):
        queryset = cls.objects.all()

        # Filtrowanie według gatunku
        if genre:
            queryset = queryset.filter(genre__genre__display_name__icontains=genre)

        # Filtrowanie według daty produkcji
        if production_year:
            queryset = queryset.filter(production_year=production_year)

        # Filtrowanie według reżysera
        if director:
            queryset = queryset.filter(directors__director__director_id=director)

        return queryset


    @classmethod
    def sort_movies(cls, genre=None, production_year=None, director=None, sort_by='rating'):
        # Przekazanie wszystkich parametrów do `query_movies`
        movies = cls.query_movies(
            genre=genre,
            production_year=production_year,
            director=director
        )

        # Sortowanie według podanego pola
        movies = movies.order_by(sort_by)

        # Przekształcenie każdego filmu na szczegóły, aby zawierał więcej danych
        movies_details = []
        for movie in movies:
            genres = Genredetails.objects.filter(genre__movie=movie)
            directors = Directorsdetails.objects.filter(directors__movie=movie)

            movie_details = {
                'movie': movie,
                'genres': genres,
                'directors': directors,

            }
            movies_details.append(movie_details)

        return movies_details


class Directors(models.Model):
    director = models.ForeignKey('Directorsdetails', models.DO_NOTHING)
    movie = models.ForeignKey('Movies', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'directors'


class Directorsdetails(models.Model):
    director_id = models.AutoField(primary_key=True)
    display_name = models.TextField()

    class Meta:
        managed = False
        db_table = 'directorsdetails'

    def __str__(self):
        return self.display_name

    @classmethod
    def get_distinct_directors(cls):
        return cls.objects.all()



class Genre(models.Model):
    genre = models.ForeignKey('Genredetails', models.DO_NOTHING)
    movie = models.ForeignKey('Movies', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'genre'

    def __str__(self):
        return self.genre.display_name


class Genredetails(models.Model):
    genre_id = models.AutoField(primary_key=True)
    display_name = models.TextField()

    class Meta:
        managed = False
        db_table = 'genredetails'

    def __str__(self):
        return self.display_name


class Moviecast(models.Model):
    celebrity = models.ForeignKey('Moviecastdetails', models.DO_NOTHING)
    movie = models.ForeignKey('Movies', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'moviecast'


class Moviecastdetails(models.Model):
    celebrity_id = models.AutoField(primary_key=True)
    display_name = models.TextField()

    class Meta:
        managed = False
        db_table = 'moviecastdetails'

review_app/models.py
from django.db import models
from user_app.models import Users
from movie_app.models import Movies



# Create your models here.
class Reviews(models.Model):
    review_id = models.AutoField(primary_key=True)
    movie = models.ForeignKey(Movies, models.DO_NOTHING)
    user = models.ForeignKey(Users, models.DO_NOTHING)
    rating = models.IntegerField()
    review_date = models.DateTimeField(auto_now=True)
    review_text = models.TextField(blank=True, null=True)


    class Meta:
        managed = False
        db_table = 'reviews'

    def get_star_rating(self):
        if self.rating is None:
            return {
                'full_stars': [],
                'half_stars': 0,
                'empty_stars': range(5)
            }
        full_stars = int(self.rating)
        decimal_part = self.rating - full_stars

        if 0.25 <= decimal_part < 0.75:
            half_stars = 1
        else:
            half_stars = 0

        empty_stars = 5 - full_stars - half_stars

        return {
            'full_stars': range(full_stars),
            'half_stars': half_stars,
            'empty_stars': range(empty_stars)
        }
    def __str__(self):
        return self.user.display_name + ' - ' + self.review_text

    @classmethod
    def get_reviews(cls):
        return cls.objects.all()

    @classmethod
    def get_reviews_head(cls):
        return cls.objects.all()[:5]

    @classmethod
    def get_review(cls, id):
        return cls.objects.get(pk=id)

    @classmethod
    def get_review_for_movie(cls, movie):
        return cls.objects.filter(movie=movie)

    @classmethod
    def get_latest_review(cls):
        return cls.objects.all().order_by('-review_date')[:3]

    @classmethod
    def query_reviews(cls, movie=None, author=None):
        if movie:
            return cls.objects.filter(movie=movie)
        if author:
            return cls.objects.filter(author__icontains=author)
        return cls.objects.all()

    @classmethod
    def sort_reviews(cls, movie, author, sort_by='rating'):
        reviews = cls.query_reviews(movie=movie, author=author)
        return reviews.order_by(sort_by)


class Moviecomments(models.Model):
    comment_id = models.AutoField(primary_key=True)
    review = models.ForeignKey(Reviews, models.DO_NOTHING)
    user = models.ForeignKey(Users, models.DO_NOTHING)
    comment_text = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'moviecomments'

    def __str__(self):
        return self.review.movie.title + ' - ' + self.user.username

    def get_comments(self):
        return self.objects.all()

    def get_comment(self, id):
        return self.objects.get(pk=id)

    def query_comments(self, review=None, user=None):
        if review:
            return self.objects.filter(review=review)
        if user:
            return self.objects.filter(user=user)
        return self.objects.all()

    def sort_comments(self, review, user):
        comments = self.query_comments(review=review, user=user)
        return comments.order_by('date')

    @classmethod
    def get_comments_for_review(cls, review_id):
        return cls.objects.filter(review__id=review_id)

movie_app/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Movies, Genredetails, Directorsdetails
from review_app.models import Reviews, Moviecomments
from django.views.decorators.http import require_POST
import requests
from django.conf import settings








# Create your views here.


def set_language(request):
    language = request.POST.get('language')
    if language in ['en', 'pl', 'de']:
        request.session['language'] = language
    # Przekierowanie na poprzednią stronę, aby odświeżyć widok
    return redirect(request.META.get('HTTP_REFERER', '/'))

def display_movie_details(request, movie_id):
    movie_details = Movies.get_movie_details(movie_id)
    reviews = Reviews.get_review_for_movie(movie_details['movie'])
    context = {
        'movie_details': movie_details,
        'reviews': reviews
    }
    return render(request, 'movie_details.html', context=context)




def display_movies(request):
    # Pobierz parametry z zapytania GET
    genre = request.GET.get('genre')
    production_year = request.GET.get('production_year')
    director = request.GET.get('director')

    sort_by = request.GET.get('sort_by', 'rating_desc')  # Domyślnie sortowanie po ratingu

    # Pobranie wszystkich dostępnych gatunków i reżyserów do listy rozwijanej
    genres = Genredetails.objects.all()
    directors = Directorsdetails.objects.all()

    # Obsługa różnych opcji sortowania
    if sort_by == 'rating_desc':
        filtered_movies = Movies.sort_movies(genre=genre, production_year=production_year, director=director, sort_by='-rating')
    elif sort_by == 'rating_asc':
        filtered_movies = Movies.sort_movies(genre=genre, production_year=production_year, director=director, sort_by='rating')
    elif sort_by == 'votes_desc':
        filtered_movies = Movies.sort_movies(genre=genre, production_year=production_year, director=director, sort_by='-votes')
    elif sort_by == 'votes_asc':
        filtered_movies = Movies.sort_movies(genre=genre, production_year=production_year, director=director, sort_by='votes')
    else:
        filtered_movies = Movies.sort_movies(genre=genre, production_year=production_year, director=director, sort_by=sort_by)

    # Ograniczenie liczby filmów do 100
    limited_movies = filtered_movies[:100]

    # Przekazanie przefiltrowanych filmów, dostępnych gatunków i reżyserów do szablonu
    return render(request, 'movies.html', {
        'movies_details': limited_movies,
        'genres': genres,
        'directors': directors,
    })


def upcoming_movies(request):
    api_key = settings.TMDB_API_KEY
    url = f'https://api.themoviedb.org/3/movie/upcoming?api_key={api_key}&language=en-EN&region=PL'

    response = requests.get(url)
    movies = response.json().get('results', [])

    base_image_url = "https://image.tmdb.org/t/p/w500"  # w500 to rozmiar obrazka
    for movie in movies:
        movie['poster_url'] = f"{base_image_url}{movie['poster_path']}"

    return render(request, 'upcoming_movies.html', {'movies': movies})

movie_app/templates/movie_details.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Movie Details" %}
{% endblock %}

{% block content %}
<div class="movie-details-container">
    <div class="movie-poster">
        <img src="{{ movie_details.movie.photo_url }}" alt="{% trans "Movie Poster" %}">
    </div>
    <div class="movie-info">
        <h1>{{ movie_details.movie.title }}</h1>
        <p><strong>{% trans "Production Year:" %}</strong> <span>{{ movie_details.movie.production_year }}</span></p>
        <p><strong>{% trans "Rating:" %}</strong> <span>{{ movie_details.movie.rating }}</span></p>
        <p><strong>{% trans "Certificate:" %}</strong> <span>{{ movie_details.movie.certificate }}</span></p>
        <p><strong>{% trans "Duration:" %}</strong> <span>{{ movie_details.movie.duration }} {% trans "minutes" %}</span></p>
        <p><strong>{% trans "Votes:" %}</strong> <span>{{ movie_details.movie.votes }}</span></p>
        <p><strong>{% trans "Genre:" %}</strong>
            {% for genre in movie_details.genres %}
                {{ genre.display_name }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p><strong>{% trans "Director:" %}</strong>
            {% for director in movie_details.directors %}
                {{ director.display_name }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p><strong>{% trans "Cast:" %}</strong>
            {% for cast in movie_details.casts %}
                {{ cast.display_name }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p><strong>{% trans "Description:" %}</strong> <span>{{ movie_details.movie.description }}</span></p>
    </div>
</div>

<h3>{% trans "Reviews" %}</h3>
<div class="reviews-container-mdetails">
    {% for review in reviews %}
        <div class="review-item-mdetails">
            <h3>{{ review.user }}</h3>
            <p>{{ review.review_text }}</p>
        </div>
        <h4>{% trans "Comments:" %}</h4>
        {% for comment in review.moviecomments_set.all %}
             <p>{{ comment.user.login }}: {{ comment.comment_text }}</p>
        {% endfor %}
        <a href="{% url 'review_app:add_comment' review_id=review.review_id %}" class="add-comment-button">{% trans "Add Comment" %}</a>
    {% endfor %}
    <a href="{% url 'review_app:add_review' movie_id=movie_details.movie.movie_id %}" class="add-review-button">{% trans "Add Review" %}</a>
</div>
{% endblock %}

movie_app/templates/movies.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Movies" %}
{% endblock %}

{% block content %}

<!-- Formularz filtrowania -->
<form method="GET" action="{% url 'movie_app:display_movies' %}" class="filter-form">
    <div class="form-group">
        <label for="genre" class="translatable">{% trans "Genre:" %}</label>
        <select name="genre" id="genre" class="form-input">
            <option value="" class="translatable">{% trans "Select Genre" %}</option>
            {% for genre in genres %}
                <option value="{{ genre.display_name }}" {% if request.GET.genre == genre.display_name %}selected{% endif %}>
                    {{ genre.display_name }}
                </option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="production_year" class="translatable">{% trans "Production Year:" %}</label>
        <input type="number" name="production_year" id="production_year" value="{{ request.GET.production_year }}" class="form-input">
    </div>
    <div class="form-group">
        <label for="director" class="translatable">{% trans "Director:" %}</label>
        <select name="director" id="director" class="form-input">
            <option value="" class="translatable">{% trans "Select Director" %}</option>
            {% for director in directors %}
                <option value="{{ director.director_id }}" {% if request.GET.director == director.director_id|stringformat:"s" %}selected{% endif %}>
                    {{ director.display_name }}
                </option>
            {% endfor %}
        </select>
    </div>
    <button type="submit" class="btn-filter translatable">{% trans "Filter" %}</button>
</form>

<!-- Formularz sortowania -->
<form method="GET" action="{% url 'movie_app:display_movies' %}" class="sort-form">
    <input type="hidden" name="genre" value="{{ request.GET.genre }}">
    <input type="hidden" name="production_year" value="{{ request.GET.production_year }}">
    <input type="hidden" name="director" value="{{ request.GET.director }}">
    <input type="hidden" name="cast" value="{{ request.GET.cast }}">

    <div class="form-group">
        <label for="sort_by" class="translatable">{% trans "Sort by:" %}</label>
        <select name="sort_by" id="sort_by" class="form-input">
            <option value="rating_desc" {% if request.GET.sort_by == 'rating_desc' %}selected{% endif %} class="translatable">{% trans "Rating Descending" %}</option>
            <option value="rating_asc" {% if request.GET.sort_by == 'rating_asc' %}selected{% endif %} class="translatable">{% trans "Rating Ascending" %}</option>
            <option value="votes_desc" {% if request.GET.sort_by == 'votes_desc' %}selected{% endif %} class="translatable">{% trans "Votes Descending" %}</option>
            <option value="votes_asc" {% if request.GET.sort_by == 'votes_asc' %}selected{% endif %} class="translatable">{% trans "Votes Ascending" %}</option>
        </select>
    </div>
    <button type="submit" class="btn-sort translatable">{% trans "Sort" %}</button>
</form>


<h3>{% trans "Movies" %}</h3>

<div class="movie-card-container">
    {% for movie_details in movies_details %}
    <div class="movie-card">
        <div class="movie-card-header">
            <img src="{{ movie_details.movie.photo_url }}" class="poster" alt="{{ movie_details.movie.title }} poster">
        </div>
        <div class="movie-card-body">

         <h4>
            {% if movie_details.movie.movie_id %}
                 <a href="{% url 'movie_app:movie_details' movie_id=movie_details.movie.movie_id %}">
                    {{ movie_details.movie.title }}
                </a>
            {% else %}
                     {{ movie_details.movie.title }}
             {% endif %}
         </h4>

            <p><strong>{% trans "Year:" %}</strong> {{ movie_details.movie.production_year }}</p>
            <p><strong>{% trans "Rating:" %}</strong> {{ movie_details.movie.rating }}</p>
            <p><strong>{% trans "Votes:" %}</strong> {{ movie_details.movie.votes }}</p>
            <p><strong>{% trans "Genres:" %}</strong>
                {% for genre in movie_details.genres %}
                    {{ genre.display_name }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
            <p><strong>{% trans "Directors:" %}</strong>
                {% for director in movie_details.directors %}
                    {{ director.display_name }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
            <p><strong>{% trans "Cast:" %}</strong>
                {% for cast in movie_details.casts %}
                    {{ cast.display_name }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

movie_app/templates/search_results.html
{% extends 'base.html' %}

{% block content %}
<h1>Wyniki wyszukiwania</h1>
{% if movies %}
    <style>
        .center-table {
        margin-left:15% ;
        margin-right: auto;
        width: 60%;
        }
    </style>
    <table class="center-table">

        <tbody>
        {% for movie in movies %}
            <tr>
                <td>
                    <a href="{% url 'movie_app:movie_details' movie_id=movie.movie_id %}">{{ movie.title }}</a>

                </td>
                <td>{{ movie.production_year }}</td>
                <td>
                    {% if movie.photo_url %}
                        <a href="{% url 'movie_app:movie_details' movie_id=movie.movie_id %}"><img src="{{ movie.photo_url }}" alt="{{ movie.title }}" style="height: 100px;"></a>
                    {% else %}
                        Brak zdjęcia
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>Brak wyników dla zapytania.</p>
{% endif %}
{% endblock %}

movie_app/templates/upcoming_movies.html
{% extends "base.html" %}

{% block content %}
<h1>Upcoming Movies</h1>
<div class="upcoming-premieres-container">
    {% for movie in movies %}
        <div class="upcoming-premiere-card">
            <img src="{{ movie.poster_url }}" alt="Poster for {{ movie.title }}">
            <div class="upcoming-premiere-title">{{ movie.title }}</div>
            <p><span class="upcoming-premiere-label">Rating:</span> {{ movie.vote_average }}</p>
            <p><span class="upcoming-premiere-label">Votes:</span> {{ movie.vote_count }}</p>
            <div class="upcoming-premiere-date">Premiera: {{ movie.release_date }}</div>
            <p class="upcoming-premiere-description">{{ movie.overview }}</p>
        </div>
    {% endfor %}
</div>
{% endblock %}