movie_recommendation/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.homepage, name='home'),
    path('about/', views.about, name='about'),
    path('admin/', admin.site.urls, name='admin'),
    path('users/', include('user_app.urls')),
    path('reviews/', include('review_app.urls')),
    path('search/', views.search_view, name='search'),
    path('movies/', include(('movie_app.urls', 'movie_app'), namespace='movie_app')),
    path('movies/search/', views.search_movies, name='search_movies'),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_app/urls.py
from django.urls import path
from . import views

app_name = 'user_app'

urlpatterns = [
    path('details/<int:user_id>/', views.display_user_details_page, name='user_details'),
    path('register/', views.display_register_page, name='register'),
    path('login/', views.display_login_page, name='login'),
    path('logout/', views.display_logout_page, name='logout'),
]

user_app/models.py
from django.db import models
from movie_app.models import Movies
from django.contrib.auth.hashers import check_password as django_check_password
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.contrib.auth.hashers import make_password
from django.db.models import QuerySet


# Create your models here.
class UserManager(BaseUserManager):
    def create_user(self, login, password=None, **extra_fields):
        if not login:
            raise ValueError('The Login field must be set')
        user = self.model(login=login, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, login, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(login, password, **extra_fields)


class Users(AbstractBaseUser, PermissionsMixin):
    user_id = models.AutoField(primary_key=True)
    login = models.TextField(unique=True)
    password_hash = models.BinaryField()
    salt = models.BinaryField()
    display_name = models.TextField()
    user_role = models.CharField(default='user')
    email = models.TextField()
    first_name = models.TextField()
    surname = models.TextField()
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'login'
    REQUIRED_FIELDS = []

    objects = UserManager()

    class Meta:
        managed = False
        db_table = 'users'

    def __str__(self):
        return self.login

    @property
    def is_anonymous(self):
        return False

    @property
    def is_authenticated(self):
        return True

    @property
    def password(self):
        return bytes(self.password_hash).decode()

    def set_password(self, raw_password):
        hashed_password = make_password(raw_password)
        self.password_hash = hashed_password.encode()
        self.save()

    @property
    def last_login(self):
        return None

    @last_login.setter
    def set_last_login(self, last_login):
        pass

    @property
    def groups(self):
        return QuerySet()

    @groups.setter
    def set_groups(self, groups):
        pass

    @property
    def user_permissions(self):
        return QuerySet()

    @user_permissions.setter
    def user_permissions(self, value):
        pass

    def save(self, *args, **kwargs):
        self.display_name = f"{self.surname} {self.first_name}"
        super().save(*args, **kwargs)

    def check_password(self, raw_password):
        password_hash = self.password_hash.tobytes().decode()
        return django_check_password(raw_password, password_hash)

    @classmethod
    def get_user(cls, id):
        return cls.objects.get(pk=id)

    @classmethod
    def get_users(cls):
        return cls.objects.all()

    @classmethod
    def get_users_head(cls):
        return cls.objects.all()[:5]

    def get_user_favorite_movies(self):
        return self.favouritemovies_set.all()

    @classmethod
    def get_users_head(cls):
        return cls.objects.all()[:5]

    def get_user_reviews(self):
        return self.reviews_set.all()

    def get_user_comments(self):
        return self.comments.all()

    @classmethod
    def query_users(cls, login=None, display_name=None):
        if login:
            return cls.objects.filter(username__icontains=login)
        if display_name:
            return cls.objects.filter(email__icontains=display_name)
        return cls.objects.all()

    @classmethod
    def sort_users(cls, username, email, sort_by='date_joined'):
        users = cls.query_users(username=username, email=email)
        return users.order_by(sort_by)


class Favouritemovies(models.Model):
    favourite_id = models.AutoField(primary_key=True)
    movie = models.ForeignKey(Movies, models.DO_NOTHING)
    user = models.ForeignKey(Users, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'favouritemovies'

user_app/forms.py
from django import forms
from .models import Users
from django.contrib.auth.hashers import make_password

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = Users
        fields = ['login', 'password', 'email', 'first_name', 'surname']
        widgets = {
            'password': forms.PasswordInput(),
        }
    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        password_hash = make_password(self.cleaned_data['password'])
        user.password_hash = password_hash.encode('utf-8')
        if commit:
            user.save()
        return user

user_app/views.py
from django.db import IntegrityError
from django.shortcuts import render, redirect
from .models import Users
from .forms import UserRegistrationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages


@login_required(login_url='user_app:login')
def display_user_details_page(request, user_id):
    user = Users.get_user(user_id)
    user_favorite_movies = user.get_user_favorite_movies()
    user_reviews = user.get_user_reviews()
    context = {'user': user, 'user_favorite_movies': user_favorite_movies,
               'user_reviews': user_reviews}
    if not request.user.is_authenticated:
        messages.info(request, 'You need to log in to see the user details page.')
    return render(request, 'user_details.html', context=context)


def display_login_page(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['login']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        print("username: ", username, "password: ", password, "user: ", user)
        if user is not None:
            login(request, user)
            return redirect('user_app:user_details', user_id=user.user_id)
        else:
            context['error'] = "Invalid username or password"
    else:
        form = AuthenticationForm()
        context['form'] = form
    return render(request, 'login.html', context=context)


def display_logout_page(request):
    logout(request)
    return redirect('home')


def display_register_page(request):
    print(f"users: {Users.get_users()}")
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            try:
                login(request, form.save())
                return redirect('user_app:login')
            except IntegrityError:
                form.add_error(None, "A user with this login already exists.")
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'register.html', context=context)

user_app/templates/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block content %}
<h1>Login Page</h1>
<form action="{% url 'user_app:login' %}" method="post" class="login-form">
    {% csrf_token %}
    <div class="form-group">
        <label for="login" class="form-label">Login:</label>
        <input type="text" id="login" name="login" required class="form-input">
    </div>
    <div class="form-group">
        <label for="password" class="form-label">Password:</label>
        <input type="password" id="password" name="password" required class="form-input">
    </div>
    <div class="form-group">
        <input type="submit" value="Login" class="login-button">
    </div>
</form>
{% if error %}
    <p class="error">{{ error }}</p>
{% endif %}
<a href="/users/register" class="register-button">Register Page</a>
{% endblock %}

user_app/templates/register.html
{% extends 'base.html' %}

{% block title %}
    Register
{% endblock %}

{% block content %}
<h1>Register Page</h1>
<form action="{% url 'user_app:register' %}" method="post" class="register-form">
    {% csrf_token %}
    <div class="form-group">
        <label for="login" class="form-label">Login:</label>
        <input type="text" id="login" name="login" required class="form-input">
    </div>
    <div class="form-group">
        <label for="password" class="form-label">Password:</label>
        <input type="password" id="password" name="password" required class="form-input">
    </div>
    <div class="form-group">
        <label for="email" class="form-label">Email:</label>
        <input type="email" id="email" name="email" required class="form-input">
    </div>
    <div class="form-group">
        <label for="first_name" class="form-label">First Name:</label>
        <input type="text" id="first_name" name="first_name" required class="form-input">
    </div>
    <div class="form-group">
        <label for="surname" class="form-label">Surname:</label>
        <input type="text" id="surname" name="surname" required class="form-input">
    </div>
    <div class="form-group">
        <input type="submit" value="Register" class="register-page-button">
    </div>
</form>
{% endblock %}

user_app/templates/user_details.html
{% extends 'base.html' %}

{% block title %}
About
{% endblock %}

{% block content %}
<main>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-info">{{ message }}</div>
        {% endfor %}
    {% endif %}
    <div class="user-details-container">

        <h1>User Details Page</h1>
        <p>Here you can see the details of the user.</p>


        <section class="user-data-section">
            <h3>User Data</h3>
            <div class="user-data-table-container">
                <table class="user-data-table">
                    <tr>
                        <th>Login</th>
                        <td>{{ user.login }}</td>
                    </tr>
                    <tr>
                        <th>User Role</th>
                        <td>{{ user.user_role }}</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>{{ user.email }}</td>
                    </tr>
                    <tr>
                        <th>First Name</th>
                        <td>{{ user.first_name }}</td>
                    </tr>
                    <tr>
                        <th>Surname</th>
                        <td>{{ user.surname }}</td>
                    </tr>
                </table>
            </div>
        </section>

        <section class="reviews-section">
            <h3>Reviews</h3>
            <div class="review-grid-det">
                {% for review in user_reviews %}
                <div class="review-item-det">
                    <h4>Movie: {{ review.movie }}</h4>
                    <p>User: {{ review.user }}</p>
                    <p>Rating: {{ review.rating }}</p>
                    <p>Date: {{ review.review_date }}</p>
                    <p>{{ review.review_text }}</p>
                </div>
                {% endfor %}
            </div>
        </section>

        <section class="favorite-movies-section">
            <h3>Favourite Movies</h3>
            <div class="review-grid-det">
                {% for review in user_reviews %}
                <div class="review-item-det">
                    <h4>Movie: {{ review.movie }}</h4>
                    <p>User: {{ review.user }}</p>
                    <p>Rating: {{ review.rating }}</p>
                    <p>Date: {{ review.review_date }}</p>
                    <p>{{ review.review_text }}</p>
                </div>
                {% endfor %}
            </div>
        </section>

    </div>
</main>
{% endblock %}

user_app/templates/users.html
{% extends 'base.html' %}

{% block title %}
Users
{% endblock %}

{% block content %}
<h1>User Page</h1>
<p>Here you can see the details of all users.</p>
<h3>Users</h3>

<table>
    <tr>
        <th>user_id</th>
        <th>login</th>
        <th>password_hash</th>
        <th>salt</th>
        <th>display_name</th>
        <th>user_role</th>
        <th>email</th>
        <th>first_name</th>
        <th>surname</th>
    </tr>
    {% for user in users %}
    <tr>
        <td>{{ user.user_id }}</td>
        <td>
            <a href="{% url 'user_app:user_details' user_id=user.user_id %}">
                {{ user.login }}
            </a>
        </td>
        <td>{{ user.password_hash }}</td>
        <td>{{ user.salt }}</td>
        <td>{{ user.display_name }}</td>
        <td>{{ user.user_role }}</td>
        <td>{{ user.email }}</td>
        <td>{{ user.first_name }}</td>
        <td>{{ user.surname }}</td>
    </tr>
    {% endfor %}
</table>
<h3>Reviews</h3>
<table>
    <tr>
        <th>review_id</th>
        <th>movie</th>
        <th>user</th>
        <th>rating</th>
        <th>review_data</th>
        <th>review_text</th>
    </tr>
    {% for review in reviews %}
    <tr>
        <td>{{ review.review_id }}</td>
        <td>{{ review.movie }}</td>
        <td>{{ review.user }}</td>
        <td>{{ review.rating }}</td>
        <td>{{ review.review_date }}</td>
        <td>{{ review.review_text }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}